In [2]:
import polars as pl

In [20]:
g_emp =(
    pl
    .read_parquet(
        '/Users/lowell/Projects/alt_nfp/data/releases.parquet'
    )
    .filter(pl.col('source').eq('qcew'))
)
g_emp

shape: (0, 11)
┌────────┬────────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ source ┆ seasonally ┆ geographic ┆ geographic ┆ … ┆ vintage_d ┆ revision ┆ benchmark ┆ employmen │
│ ---    ┆ _adjusted  ┆ _type      ┆ _code      ┆   ┆ ate       ┆ ---      ┆ _revision ┆ t         │
│ str    ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ u8       ┆ ---       ┆ ---       │
│        ┆ bool       ┆ str        ┆ str        ┆   ┆ date      ┆          ┆ u8        ┆ f64       │
╞════════╪════════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
└────────┴────────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [15]:
g_births = (
    pl
    .read_parquet(
        '/Users/lowell/Projects/alt_nfp/data/raw/providers/G/g_panel.parquet'
    )
    .rename({'geographic_type': 'geography_type', 'geographic_code': 'geography_code'})
)
g_births

shape: (1_066, 6)
┌────────────┬────────────────┬────────────────┬───────────────┬───────────────┬────────────┐
│ ref_date   ┆ geography_type ┆ geography_code ┆ industry_type ┆ industry_code ┆ employment │
│ ---        ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---        │
│ date       ┆ str            ┆ str            ┆ str           ┆ str           ┆ i32        │
╞════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪════════════╡
│ 2019-04-12 ┆ national       ┆ 00             ┆ domain        ┆ 06            ┆ 32806      │
│ 2019-04-12 ┆ national       ┆ 00             ┆ domain        ┆ 07            ┆ 273744     │
│ 2019-04-12 ┆ national       ┆ 00             ┆ national      ┆ 00            ┆ 306550     │
│ 2019-04-12 ┆ national       ┆ 00             ┆ supersector   ┆ 10            ┆ 469        │
│ 2019-04-12 ┆ national       ┆ 00             ┆ supersector   ┆ 20            ┆ 10861      │
│ …          ┆ …              ┆ …              ┆ …             ┆ …             ┆ …          │
│ 2026-01-12 ┆ national       ┆ 00             ┆ supersector   ┆ 55            ┆ 66977      │
│ 2026-01-12 ┆ national       ┆ 00             ┆ supersector   ┆ 60            ┆ 254056     │
│ 2026-01-12 ┆ national       ┆ 00             ┆ supersector   ┆ 65            ┆ 298013     │
│ 2026-01-12 ┆ national       ┆ 00             ┆ supersector   ┆ 70            ┆ 160430     │
│ 2026-01-12 ┆ national       ┆ 00             ┆ supersector   ┆ 80            ┆ 122857     │
└────────────┴────────────────┴────────────────┴───────────────┴───────────────┴────────────┘

In [17]:
g_file = (
    g_births
    .join(
        g_emp,
        on=['ref_date', 'geography_type', 'geography_code', 'industry_type', 'industry_code'],
        how='inner'
    )
)

(
    g_file
    .write_parquet(
        '/Users/lowell/Projects/alt_nfp/data/raw/providers/G/g_provider.parquet'
    )
)